version: '3.3'
services:
  elasticserver:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.4
    container_name: elastic_server
    environment:
      - http.host=0.0.0.0
      - transport.host=127.0.0.1
      - xpack.security.enabled=false
    ports:
      - 9200:9200
  elasticclient:
    image: search:latest
    ports:
      - 8092:8092
    container_name: elastic_client
    depends_on:
      - elasticserver
